//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYLTRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GYLTEntities : DbContext
    {
        public GYLTEntities()
            : base("name=GYLTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WeightEntry> WeightEntries { get; set; }
        public virtual DbSet<WeightLossAttempt> WeightLossAttempts { get; set; }
        public virtual DbSet<WeightLossMilestone> WeightLossMilestones { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
