//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYLTRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightLossAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeightLossAttempt()
        {
            this.WeightEntries = new HashSet<WeightEntry>();
            this.WeightLossMilestones = new HashSet<WeightLossMilestone>();
        }
    
        public int WeightLossAttemptID { get; set; }
        public System.DateTimeOffset DateCreated { get; set; }
        public Nullable<System.DateTimeOffset> DateDeleted { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public decimal StartingWeight { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<decimal> TargetWeight { get; set; }
        public string Goal { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeightEntry> WeightEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeightLossMilestone> WeightLossMilestones { get; set; }
        public virtual User User { get; set; }
    }
}
